services:
  - type: web
    name: chan-analysis-web
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k gthread -b 0.0.0.0:$PORT web.app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PIP_NO_BUILD_ISOLATION
        value: "1"
      - key: PORT
        value: 10000
    autoDeploy: true

